### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by TheOnlyPhoenix**
add README.md for JameBot

### CODE REVIEW

**Review by jamesbt365 — APPROVED** [review]
lol

**Comment by 32-bit-link** [comment]
I disapprove 

Do not merge

**Comment by jamesbt365** [comment]
Resolve conflicts.

**Comment by jamesbt365** [comment]
oops

**Comment by jamesbt365** [comment]
Fixed it in 0d28fd0f76a794870257e9289229d7a83be2c839

**Comment by 32-bit-link** [comment]
These images suck + Default commit name 🤓 🤓 🤓 🤓 🤓

**Pull request merged**
